Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@LucasSMguerrabr 
duribeiro
/
duribeiro
Public
Fork your own copy of duribeiro/duribeiro
Code
Pull requests
Actions
Projects
Security
Insights
duribeiro/.github/workflows/snake.yml
@duribeiro
duribeiro Create snake.yml
Latest commit 2f400e7 on Oct 29, 2021
 History
 1 contributor
26 lines (22 sloc)  585 Bytes

name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: LucasSMguerrabr
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

